#
###################################
# Site wide configuration
####################################
#
title: Thien Hoang
email: thienvhoang99@gmail.com
description: Blog
url: https://hoangvanthien.github.io/ # the base hostname & protocol for your site
keywords: ["Programming", "Algorithm", "Mathematics"]

#
###################################
# Jekyll configuration
####################################
#
timezone: "Asia/Ho_Chi_Minh"
markdown: kramdown
highlighter: rouge
excerpt_separator: <!--more-->
permalink: articles/:year/:month/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: Thien Hoang
  avatar:
  job: "Student"
  bio: "Studying Computer Science at Vietnamese-German University"
  email: thienvhoang99@gmail.com
  disqus-shortname: thelazycat
  twitter: ThienVHoang
  facebook: hvt99
  google:
    analytics: "UA-99578582-2"
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: hoangvanthien
  stackoverflow:
  linkedin:
  xing:
  instagram: thelazycat__
  lastfm:
  tumblr:
  pinterest:
  foursquare:
  steam:
  dribbble:
  youtube:
  soundcloud:
  weibo:
  flickr:
  codepen:
  telegram:

exclude:
  - LICENSE
  - README.md

plugins:
  - jekyll-paginate

paginate: 5
paginate_path: "/page:num/"
